### ISSUE TITLE
Join code

### ISSUE THREAD

**Issue by audreylemeur** [mn-pollinators/buzz-about#144]
Generate and display shorter join codes so it's easier to join a session. Ideally, a 6-digit number split into two 3-digit numbers.

**Comment by floogulinc** [comment]
Our notes from today's meeting:

joinCodes collection
- ID is six-digit joinCode
- has creation/update timestamp
- has ID of session

rules for documents in the joinCodes collection:
- can always be created
- can be updated (to point to a different session) if non-active
  - to allow re-using old expired join codes
  - maybe "can be updated if it's non-active and it hasn't been active for a certain additional amount of time".
- can be deleted if user is owner of referenced session ID
- can be gotten by ID if "active"
- can be gotten by query ("listed") if user is owner of references session ID and joinCode is active

teacher flow:
- session created
- session lobby has button to create joinCode
  - this button creates joinCode in joinCodes collection using the `set()` function with generated 6 digit ID
  - if there is an error it retries multiple times
  - after a certain number of retries, we give up and show an error snackbar
  - we expect that collisions shouldn't be too likely, since join codes have a short lifespan (there aren't too many of them active at once).
- joinCode can be removed by teacher at any time
  - we can figure out the UI for that later

student flow:
- student enters join code on join page
- tries to get that join code document from the joinCodes collection
- if we get the join code successfully (which only happens of the join code is active), we read its session ID field
- then we join that session as normal.

("active" means "created not more than 3 hour ago" or something like that.)
